grab_obj_name = [
    'elephant', 'headphones', 'cylinderlarge', 'hand', 'spherelarge', 
    'toruslarge', 'wristwatch', 'stapler', 'flute', 'table', 
    'train', 'pyramidmedium', 'wineglass', 'scissors', 'gamecontroller', 
    'spheresmall', 'pyramidsmall', 'knife', 'mouse', 'torusmedium', 
    'watch', 'cylindermedium', 'phone', 'banana', 'cylindersmall', 
    'apple', 'toothbrush', 'coffeemug', 'bowl', 'cup', 
    'cubemedium', 'pyramidlarge', 'cubesmall', 'alarmclock', 'teapot', 
    'duck', 'camera', 'waterbottle', 'airplane', 'fryingpan', 
    'body', 'lightbulb', 'torussmall', 'stamp', 'hammer', 
    'spheremedium', 'binoculars', 'doorknob', 'toothpaste', 'cubemiddle', 
    'stanfordbunny', 'cubelarge', 'piggybank', 'mug', 'rubberduck', 
    'eyeglasses', 'flashlight'
]

object_proc = {
    "fryingpan": "frying pan", 
    "waterbottle": "water bottle", 
    "cubelarge": "cube",
    "cubemedium": "cube", 
    "cubesmall": "cube", 
    "cylinderlarge": "cylinder", 
    "cylindermedium": "cylinder", 
    "cylindersmall": "cylinder", 
    "pyramidlarge": "pyramid", 
    "pyramidmedium": "pyramid", 
    "pyramidsmall": "pyramid", 
    "spherelarge": "sphere", 
    "spheremedium": "sphere", 
    "spheresmall": "sphere", 
    "stanfordbunny": "stanford bunny", 
    "toruslarge": "torus", 
    "torusmedium": "torus", 
    "torussmall": "torus", 
    "gamecontroller": "game controller", 
    "piggybank": "piggy bank", 
    "alarmclock": "alarm clock", 
    "lightbulb": "light bulb", 
}

motion_proc = {
    "offhand": "hand over", 
    "switchON": "switch on", 
    "takepicture": "take picture", 
}

present_participle = {
    'hand over': 'handing over', 
    'browse': 'browsing',
    'brush': 'brushing',
    'call': 'calling',
    'chop': 'chopping',
    'clean': 'cleaning',
    'cook': 'cooking',
    'drink': 'drinking',
    'eat': 'eating',
    'fly': 'flying',
    'inspect': 'inspecting',
    'lift': 'lifting',
    'open': 'opening',
    'pass': 'passing',
    'peel': 'peeling',
    'play': 'playing',
    'pour': 'pouring',
    'screw': 'screwing',
    'see': 'seeing',
    'set': 'setting',
    'shake': 'shaking',
    'squeeze': 'squeezing',
    'stamp': 'stamping',
    'staple': 'stapling',
    'switch on': 'switching on',
    'take picture': 'taking picture',
    'toast': 'toasting',
    'use': 'using',
    'wear': 'wearing'
}

third_verb = {
    'hand over': 'hands over', 
    'browse': 'browses',
    'brush': 'brushes',
    'call': 'calls',
    'chop': 'chops',
    'clean': 'cleans',
    'cook': 'cooks',
    'drink': 'drinks',
    'eat': 'eats',
    'fly': 'flies',
    'inspect': 'inspects',
    'lift': 'lifts',
    'open': 'opens',
    'pass': 'passes',
    'peel': 'peels',
    'play': 'plays',
    'pour': 'pours',
    'screw': 'screws',
    'see': 'sees',
    'set': 'sets',
    'shake': 'shakes',
    'squeeze': 'squeezes',
    'stamp': 'stamps',
    'staple': 'staples',
    'switch on': 'switches on',
    'take picture': 'takes picture',
    'toast': 'toasts',
    'use': 'uses',
    'wear': 'wears'
}

passive_verb = {
    'hand over': 'handed over', 
    'browse': 'is browsed',
    'brush': 'is brushed',
    'call': 'is called',
    'chop': 'is chopped',
    'clean': 'is cleaned',
    'cook': 'is cooked',
    'drink': 'is drunk',
    'eat': 'is eaten',
    'fly': 'is flown',
    'inspect': 'is inspected',
    'lift': 'is lifted',
    'open': 'is opened',
    'pass': 'is passed',
    'peel': 'is peeled',
    'play': 'is played',
    'pour': 'is poured',
    'screw': 'is screwed',
    'see': 'is seen',
    'set': 'is set',
    'shake': 'is shaken',
    'squeeze': 'is squeezed',
    'stamp': 'is stamped',
    'staple': 'is stapled',
    'switch on': 'is switched on',
    'take picture': 'is pictured',
    'toast': 'is toasted',
    'use': 'is used',
    'wear': 'is worn'
}