h2o_obj_name = [
    '', 'book', 'espresso', 'lotion', 'spray',
    'milk', 'cocoa', 'chips', 'cappuccino', 
]

action_list = [
    "background",
    "grab book",
    "grab espresso",
    "grab lotion",
    "grab spray",
    "grab milk",
    "grab cocoa",
    "grab chips",
    "grab cappuccino",
    "place book",
    "place espresso",
    "place lotion",
    "place spray",
    "place milk",
    "place cocoa",
    "place chips",
    "place cappuccino",
    "open lotion",
    "open milk",
    "open chips",
    "close lotion",
    "close milk",
    "close chips",
    "pour milk",
    "take out espresso",
    "take out cocoa",
    "take out chips",
    "take out cappuccino",
    "put in espresso",
    "put in cocoa",
    "put in cappuccino",
    "apply lotion",
    "apply spray",
    "read book",
    "read espresso",
    "spray spray",
    "squeeze lotion",
]

present_participle = {
    "grab": "grabbing",  
    "place": "placing", 
    "open": "openning", 
    "close": "closing", 
    "pour": "pouring", 
    "take out": "taking out", 
    "put in": "putting in", 
    "apply": "applying", 
    "read": "reading", 
    "spray": "spraying",
    "squeeze": "squeezing", 
}

third_verb = {
    "grab": "grabs", 
    "place": "places", 
    "open": "opens", 
    "close": "closes", 
    "pour": "pours", 
    "take out": "takes take", 
    "put in": "puts in", 
    "apply": "applies", 
    "read": "reads", 
    "spray": "sprays",
    "squeeze": "squeezes", 
}

passive_verb = {
    "grab": "is grabbed", 
    "place": "is placed", 
    "open": "is opened", 
    "close": "is closed", 
    "pour": "is poured", 
    "take out": "is taken out", 
    "put in": "is put in", 
    "apply": "is applied", 
    "read": "is read", 
    "spray": "is sprayed",
    "squeeze": "is squeezed", 
}