model_name: refiner
hand_input_nfeats: 2273 # 
hand_output_nfeats: 99 # 99 # 3 + 16*6
latent_dim: 512
ff_size: 1024
num_layers: 8
num_heads: 4
dropout: 0.1
activation: gelu
clip_dim: 512
obj_dim: 1024
cond_mask_prob: 0.1
use_cond_fc: True
use_obj_scale_centroid: True
zero_initialized: True
global_feat: True
feature_transform: False
in_dim: 4
iteration: 3000
lr: 0.0001
contact_loss_type: l1
lambda_simple: 1.0 # 0 1
lambda_penet: 1.0
lambda_contact: 5.0
save_root: outputs/${refiner.model_name}
weight_path: checkpoints/${dataset.name}/${refiner.model_name}.pth